### ISSUE TITLE
Can call `checkIn()` multiple times

### ISSUE THREAD

**Issue by wolever** [SpankChain/spankbank#15]
`checkin()` can be called multiple times, which will incorrectly increment the next period’s `totalSpankPoints`: https://github.com/SpankChain/spankbank/blob/master/contracts/SpankBank.sol#L281 (edited)

I believe that `require(staker.spankPoints[currentPeriod + 1] == 0)` should be sufficient to fix.

**Comment by zitatende** [comment]
It might be desirable, though, to be able to check in repeatedly per period:
Someone might first check in (without extending) just to secure their Booty for the next period, and then, later on in the same period, they might decide to extend their stake.

I'd therefore suggest fixing the issue not by denying multiple check-ins, but by properly adjusting the total Spank points, that is, subtracting the old value of `staker.spankPoints[currentPeriod + 1]` from the next period's total Spank points.
