### ISSUE TITLE
use SPANK token `approveAndCall`

### ISSUE THREAD

**Issue by ameensol** [SpankChain/spankbank#3]
Nathan:

having initial thoughts that `approveAndCall()` on Spank token will be how to handle msig bank deposits. Just msig an `approveAndCall()` and implement the correct fallback interface `receiveApproval()` to entrypoint into `stake(amt, time)`. Just use `_extraData` parameter in the call to send over the number of periods to stake for?

yes, so Spank token calls `receiveApproval(address,uint256,address,bytes)` where address is the msig, so we would use the address param in `receiveApproval()` to register the staker

**Comment by jamesyoung** [comment]
yes, also validate SPANK token address and encode _extraData properly. More on encoding _extraData can be found here https://github.com/ConsenSys/Tokens/pull/45
