### ISSUE TITLE
update burn functions

### ISSUE THREAD

**Issue by ameensol** [SpankChain/spankbank#4]
Right now I copied the burn functions from open zeppelin [Burnable.sol](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/token/ERC20/BurnableToken.sol) into Mintable.sol, but this is not an acceptable long-term solution. 

Also - we don't want `burn` to be public the way it is in Burnable.sol because that would circumvent the spankbank fee collection and tracking. We want only the owner of the BOOTY token (the spankbank) to be able to call burn.

**Comment by jamesyoung** [comment]
going to update `Mintable.sol` to `MintAndBurn.sol`
