### ISSUE TITLE
Dangerous stake method usage

### ISSUE THREAD

**Issue by k06a** [SpankChain/spankbank#49]
Hi, `approveAndCall` method is not in ERC20 and potentially some unofficial clients (web/mobile/desktop) may try to make 2 transactions as well as `stake` method is public:
1. The first Tx to `approve` bank some amount of tokens
2. The second Tx to call `stake` public method, which will `transferFrom` previously approved tokens

And anyone will be able to spend anyone tokens right between this transaction. If you're sure everybody will everytime use `approveAndCall` so why do you need `stake` method at all? Why do you need it even exist?

**Comment by ameensol** [comment]
We put `stake` in the contract specifically _for_ third-party UIs which prefer to use the `approve` -> `stake` flow over `approveAndCall`. 

> And anyone will be able to spend anyone tokens right between this transaction

I don't think this is true, only the SpankBank would be approved, and the only way to get the SpankBank to trigger a `transferFrom` on the SPANK contract is to call `stake`.

**Comment by k06a** [comment]
@ameensol I will be able to call `receiveApproval` manually for your `approve` and I will be able to setup your stake.

**Comment by k06a** [comment]
I will be able to set any arguments I want for your stake:
- `uint256 spankAmount`
- `uint256 stakePeriods`
- `address delegateKey`
- `address bootyBase`

**Comment by k06a** [comment]
@ameensol let's reopen the issue :)

**Comment by k06a** [comment]
Someone could use this scheme to intervene your users to work with spankbank.

**Comment by k06a** [comment]
This bug is not critical, by IMHO it is major.

**Comment by k06a** [comment]
I'd recommend looking at ERC1003 for solution fully compatible with ERC20 two-transaction mode: https://github.com/ethereum/EIPs/issues/1003

**Comment by k06a** [comment]
Looks like stacked BOOTY can be stolen in case of setting hackers `bootyBase` address

**Comment by ameensol** [comment]
This is a good catch. 

> I will be able to call receiveApproval manually for your approve and I will be able to setup your stake.

You would indeed be able to do this.

```
    function receiveApproval(address from, uint256 amount, address tokenContract, bytes extraData) SpankBankIsOpen public returns (bool success) {
        address delegateKeyFromBytes = extraData.toAddress(12);
        address bootyBaseFromBytes = extraData.toAddress(44);
        uint256 periodFromBytes = extraData.toUint(64);

        emit ReceiveApprovalEvent(from, tokenContract);

        doStake(from, amount, periodFromBytes, delegateKeyFromBytes, bootyBaseFromBytes);
        return true;
    }
```

This could be solved by checking inside the `receiveApproval` function that the `msg.sender` is the BOOTY ERC20 contract (`bootyToken.address`).

**Comment by k06a** [comment]
Also hacker can vote for closing for some of the participants. Trying to enumerate all possible attack vectors.

**Comment by ameensol** [comment]
Hey, we fixed this as part of a more critical bugfix. 

https://medium.com/spankchain/spankbank-hotfix-5bca5bfd288d

Send me an ETH address and I'll send you $1,000 worth of ETH as a reward.

Thanks!
