### ISSUE TITLE
Delegate address are public? a bug or a feature!

### ISSUE THREAD

**Issue by drhus** [SpankChain/spankbank#51]
I thought the whole idea of **Delegate address** is security and privacy! so why it's public then ex. https://bank.spankchain.com/staker/0x974b18ec8fc25a89225cc24720ff08ac878600c2

**Comment by ChaceHunter** [comment]
The Delegate key exists more for convenience when managing staking from either a multisig wallet or staking from multiple wallets. The security exists in being able to manage your checkins and BOOTY claims from a different wallet different than your staking address.

There's not really any privacy benefits as everything still remains publicly visible on the Ethereum blockchain; including everything in the SpankBank smart contract.

The staker profile link you provided is unique to each staker's address, and remains pseudonymous as long as you don't share it publicly.
