### ISSUE TITLE
Only working with Infura network

### ISSUE THREAD

**Issue by LukeWheeldon** [SpankChain/spankbank#61]
Using SpankBank with anything but Infura will result in the following error when attempting to "Connect to Metamask":

<img width="526" alt="Screen Shot 2020-05-27 at 08 36 58" src="https://user-images.githubusercontent.com/61089799/83034697-c50d2b80-9ff5-11ea-83ba-d0b4bf9a04e6.png">

Easily replicable by adding https://cloudflare-eth.com/ as a Custom RPC in Metamask.

**Comment by cheese666** [comment]
Can someone help me?? I am getting the same error no matter what I use. I would get it occasionally but I have not been able to access my tokens in a few weeks now.
